### ISSUE TITLE
How about categorize third-party plugins

### ISSUE THREAD

**Issue by yurenchen000** [gnome-terminator/docs#13]
list by categories,
make it easier for readers to find the plugin they want
maybe.

![terminator_categorize_plugin](https://user-images.githubusercontent.com/8458213/203375398-e935edd0-7750-4eab-8872-15fd86779238.png)

RP
https://github.com/yurenchen000/docs/blob/master/source/plugins.rst#third-party-plugins

**Comment by mattrose** [comment]
That looks great, can you open a PR?

**Comment by mattrose** [comment]
nm, found it.
