### ISSUE TITLE
Link to plugin creating tutorial doesn't work

### ISSUE THREAD

**Issue by pktiuk** [gnome-terminator/docs#6]
Tutorial from here https://gnome-terminator.readthedocs.io/en/latest/plugins.html#creating-your-own-plugins

> The following guide is initially sourced from a tutorial written by Chris Jones back in April 2010. I’m reproducing it here as a precaution, although I don’t expect the original will disappear. It will get rewritten and expanded as more knowledge and information is added.

Leads to non-existing page (404)

**Comment by mattrose** [comment]
fixed now
